config/routes.rb
Hackplus::Application.routes.draw do
  
  match '/signup', to: 'users#new'

  root :to => 'demo2#index'
  resources :users do
    resources :tasks
  end
  resources :tasks do
    put 'complete', on: :member
    put 'uncomplete', on: :member
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
 
  match '/users/:id/edit' => 'users#edit'
  match '/users/:id/' => 'users#show'
  match '/signin' => 'sessions#new'
  match 'users/:id/newtask' => 'tasks#new'
  match 'newtask' => 'tasks#new'

  match 'tasks/:id/complete' => 'tasks#complete'
  match 'tasks/:id/uncomplete' => 'tasks#uncomplete'

  match '/tasks/:id/' => 'tasks#index'

  match '/signout' => 'sessions#destroy', via: :delete

end

app/models/demo2.rb
class Demo2 < ActiveRecord::Base
  # attr_accessible :title, :body
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :description, :name, :duetime, :length, :interest, :user
  validates :name, presence: true, length: {maximum:60}
  validates :description, presence: true, length: {maximum:1000}
  validates :interest, presence: true
  validates :length, presence: true


  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  before_save { self.email = email.downcase }
  before_save :create_remember_token
  has_many :tasks
  validates :name, presence: true, length: {maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i #found it online, basic checking for format
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true

  has_secure_password

  private

  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
  	sign_out
  	super
  end
end

app/controllers/demo2_controller.rb
class Demo2Controller < ApplicationController
	def sortTasksbyPriority
    	@user = User.find(params[:id])
    	@user.tasks.order("interest DESC").all
    	redirect_to root_url
  	end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
	def new
	end
	def sortTasksbyPriority
        @user = User.find(params[:id])
        @user.tasks.order("interest DESC").all
        redirect_to root_url
    end
    helper_method :sortTasksbyPriority
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to root_url
		else
			flash[:error] = 'Invalid email/password combination'
			redirect_to signin_path
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@task = Task.new
	end

	def show
		@task = Task.find(params[:id])
	end

	def create
		@task = Task.new(params[:task])
		if @task.save
			params[:task][:duetime] = DateTime.strptime(params[:task][:duetime], 
												"%m/%d/%Y %H:%M:%S %p")
			#make time attribute follow this pattern instead
			@user = User.find(params[:task][:id])

			@user.tasks.create(params[:task])

			flash[:success] = "Task Saved."
			redirect_to root_url
		else
			render 'new'
		end
	end
	

	def destroy
		@task = Task.find(params[:id])
		@task.delete
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js
		end
	end

	def complete
		@task = Task.find(params[:id])
		@task.update_attribute(:completed, true)
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js
		end
	end

	def uncomplete
		@task = Task.find(params[:id])
		@task.update_attribute(:completed, false)
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to Task+!"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated successfully!"
      sign_in @user
      redirect_to root_url
    else
      render 'edit'
    end
  end


  

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

  helper_method :sortTasksbyPriority
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo2_helper.rb
module Demo2Helper
  class TaskFormBuilder < ActionView::Helpers::FormBuilder
  def text_field(attribute, options={})
    label(attribute) + super
  end
end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
		#||= is an operator that assigns @current_user only if it is undefined
	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
	def calcPriority(task)
		currenttime = Time.now
		duetime = task.duetime
		diff = (currenttime - duetime)/1.hour
		if(diff < 0.1) 
			diff = 0.1
		end
		#returns a float between 0 and 10
		return 1.0 / diff
	end 

	def calcTimeEfficiency(task, priority)
		priority =  priority**2
		interest =  task.interest**2
		length = task.length
		return ((priority + interest)**0.5 / length).round(2)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/demo2/_header.html.erb
<% if (not signed_in?) and (request.original_url.split('/')[3]  == "/newtask")%> <!-- checks if user is logged in -->
  <script type="text/javascript">
    window.location.href="/signin"; // put your correct path in a string here
  </script>
<% end %>
<html>
<head>

<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "custom" %>
<link href='http://fonts.googleapis.com/css?family=Kite+One|Dosis|Open+Sans' rel='stylesheet' type='text/css'>

<title> Hackplus </title>
</head>

<!-- Fixed navbar -->
      
      <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container">
          <div class = "row-fluid">
          <span class = "span4">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Task+</a>
            </div>
            </span>
            
            <span class = "span2 offset6">
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav" style = "margin-top: 5px;">
                    <% if signed_in? %>


                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                        <ul class="dropdown-menu">
                        
                          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                          <li><a href="newtask">New Task</a></li>
                          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
      
                        </ul>
                      </li>

                    <% else %>
                      <li class = "dropdown">
                      <a href ='#' class = "dropdown-toggle" data-toggle="dropdown"> Sign In </a>
                      <ul class = "dropdown-menu wide">
                      <li>
     
                          <%= form_for(:session, url: sessions_path, html: { class: "form-dropdown"}) do |f|%>

                              <%= f.label :email, class: "sr-only" %>

                              <%= f.text_field :email, class:"input-block-level", placeholder:"Email" %>

                              <%= f.label :password, class: "sr-only" %>
                              <%= f.password_field :password, class:"input-block-level", placeholder:"Password" %>

                            <%= f.submit "Sign in", class: "btn btn-primary" %>
                            <input type = "button" class= "btn btn-secondary" style = "float: right" onclick= "window.location='/signup'" value = "Sign Up"/>

                           <% end %>





                     
                      </li>
                      <li>

                      </li>
                      </ul>
                                            </li>

                    <% end %>
                  </ul>
                </div><!--/.nav-collapse -->
            </span>
          </div>
        </div>
      </div>

app/views/demo2/index.html.erb
<html> 
<%= render "header" %>
<% 
if signed_in?
#write this up here so as to be more efficient
todo = [];
completed = [];

current_user.tasks.each do |task|
  unless task.completed
    todo.append(task)
  else
    completed.append(task)
  end

  todo.sort_by! {|task| calcTimeEfficiency(task, calcPriority(task))}
  todo.reverse!
  completed.sort_by! {|task| task.duetime}
  completed.reverse!
end 

end
%>

<body style = "margin-top: 60px">



      <!-- Begin page content -->
<div class="container">
    <div id = "page-block"> <!-- page container-->
      <div class ="main-container">
        <div class="page-header">
          <h2>My Tasks</h2>
        </div>
        <div class="panel panel-default">
        <div class = "accordionHead" id = "accordion3">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHead" data-target= ".new_task">
            <div class="panel-heading">
            New Task
            </div>
            </a>
        <div class="new_task collapse">

          <div id = "taskcontainer">
                <!--- main task container-->
                <ul class="list-group" id="todo_list">


          <% if signed_in? %>
          <%= form_for :task, remote: true, html: {class: "form-signin"} do |f| %>
           <h2 class="form-signin-heading">New Task</h2>

          <div class="form-group">
            <%= f.text_field :name, class:"form-control",  placeholder:"Name" %>
          </div>


          <div class="form-group">
            <%= f.text_area :description, class:"form-control", size:"10x5",  placeholder:"Description" %>
          </div>
          
          
          <div class = "form-group">
            <%= f.label :interest, class: "sr-only" %>
            <%= f.number_field :interest, placeholder: "How interesting is this task?", html: {max:"10", min: "1"}%>

          </div>  
          <div class = "form-group">
            <%= f.label :length, class: "sr-only" %>
            <%= f.number_field :length, placeholder: "How many hours will it take?", html: {max:"10", min: "1"}%>

          </div>    
          <div class="form-group">
            <div id="datetimepicker1" class="input-append date">
              <%= f.label :duetime, class: "sr-only" %>

              <%= f.text_field :duetime, class: "input-block-level", 'data-format'=> "MM/dd/yyyy HH:mm:ss PP", placeholder: "Due time"%>
              <span class="add-on">
                <i style = "height: 50px" data-time-icon="icon-time" data-date-icon="icon-calendar">
                </i>
              </span>
            </div>
          </div>
          <script type="text/javascript">
            $(function() {
              $('#datetimepicker1').datetimepicker({
                language: 'en',
                pick12HourFormat: true,
                

              });
            });
          </script>
          <div class = "form-group">
            <%= f.label :completed, class: "sr-only" %>
            <%= f.hidden_field :completed, value: false %>

          </div>
          <div class = "form-group">
            <%= f.label :id, class: "sr-only" %>
            <%= f.hidden_field :id, value: current_user.id %>

          </div>      
          
              <%= f.submit "Add Task", :onclick => "", class: "btn btn-primary" %>
        <% end %>
        <% end %>                 
                </ul>

          </div>


        </div>  
        </div>
        </div>
        <div class="panel panel-default">
        <div class = "accordionHead" id = "accordion3">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHead" data-target= ".panel-body">
            <div class="panel-heading">
            To Do
            </div>
            </a>
        <div class="panel-body collapse in">

          <div id = "taskcontainer">
                <!--- main task container-->
                <ul class="list-group" id="todo_list">


                <% if signed_in? %>
                    <div id="todo_tasks"><%= render partial: "tasks/task", collection: todo %></div>
                <% end %>                 
                </ul>

          </div>


        </div>  
        </div>
        </div>
      </div>

<div class="panel panel-default">
<div class = "accordionHead" id = "accordion3">
  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHead" data-target= ".panel-body2">
    <div class="panel-heading ">
    Completed
    </div>
  </a>

  <div class="panel-body2 collapse">
    <div id = "completedtaskcontainer">
      <!--- main task container-->
      <ul class="list-group" id="completed_list">
       
              <% if signed_in? %>
                <div id="completed_tasks"><%= render partial: "tasks/task", collection: completed %></div>
              <% end %>
      </ul>
    </div>


</div>

</div>
</div>
</div>
</div>
</body>
</html>


app/views/demo2/main.html.erb
<html> 
<%= render "header" %>

<body style = "margin-top: 50px">

<div class = "welcome">
let's make life easier
</div>

<div class="footer"> 

<div>


      <!-- Begin page content -->
      <div class="container">

      <div id = "page-container"> <!-- page container-->
      
      <div class ="main-container">


 

    </div>  
    </div>
    </div>




</body>
</html>


app/views/demo2/settings.html.erb
<html> 
<head>
<%= stylesheet_link_tag "bootstrap" %>
<%= stylesheet_link_tag "custom" %>
<title> Hackplus </title>
<style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
</head>

<body>
          <%= render "demo2/header" %>

    <div id="wrap">


      <!-- Begin page content -->
      <div class="container">
        <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="input-block-level" placeholder="Email address">
        <input type="password" class="input-block-level" placeholder="Password">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        <%= link_to "Sign Up", signup_path %>
      </form>

    </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackplus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
CTYPE html>
<!-- saved from url=(0054)http://getbootstrap.com/examples/sticky-footer-navbar/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://getbootstrap.com/assets/ico/favicon.png">

    <title>Sticky Footer Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  <style type="text/css"></style></head>

  <body style="">

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Project name</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Home</a></li>
              <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#about">About</a></li>
              <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#contact">Contact</a></li>
              <li class="dropdown">
                <a href="http://getbootstrap.com/examples/sticky-footer-navbar/#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Action</a></li>
                  <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Another action</a></li>
                  <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">Separated link</a></li>
                  <li><a href="http://getbootstrap.com/examples/sticky-footer-navbar/#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        <div class="page-header">
          <h1>Sticky footer with fixed navbar</h1>
        </div>
        <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added within <code>#wrap</code> with <code>padding-top: 60px;</code> on the <code>.container</code>.</p>
        <p>Back to <a href="http://getbootstrap.com/examples/sticky-footer">the default sticky footer</a> minus the navbar.</p>
      </div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="text-muted credit">Example courtesy <a href="http://martinbean.co.uk/">Martin Bean</a> and <a href="http://ryanfait.com/sticky-footer/">Ryan Fait</a>.</p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./Sticky Footer Navbar Template for Bootstrap_files/jquery.js"></script>
    <script src="./Sticky Footer Navbar Template for Bootstrap_files/bootstrap.min.js"></script>
  

<div id="GOOGLE_INPUT_CHEXT_FLAG" style="display: none;" input="" input_stat="{}"></div><iframe frameborder="0" scrolling="no" style="background-color: transparent; border: 0px; display: none; box-sizing: content-box; width: 427px; height: 299px; box-shadow: rgba(0, 0, 0, 0.2) 0px 4px 16px 0px; z-index: 2147483640; margin: 0px; position: fixed;"></iframe></body></html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    
    <% if object == @user %>
      <% @user.errors.add(:password_confirmation) if @user.errors.include?(:password) %>
      <% @user.errors.delete(:password_digest) %>
    <% end %>
    <div class = "alert alert-error">
    Sorry! We had some problems:
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li class="list-group-item" id="task_<%=task.id%>">
              <div class="task-interest">
              <% timeEff = calcTimeEfficiency(task, calcPriority(task)) %>
              <%= timeEff %>
              </div>

              <% if !task.completed %>
                <%= link_to "☐", complete_task_path(task), remote: true, class: "checkmark" %>
              <% else %>
                <%= link_to "☑", uncomplete_task_path(task), remote: true, class: "checkmark" %>
              <% end %>

              <div class="accordion-group">
              <div class="accordion-heading">
                          <div class = "row">
                              <div class ="col-md-4">
                                  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" data-target= "#<%= task.id %>">
                            
                                      <div class="task-name">
                                          <%= task.name %>
                                      </div>    
                            
                                      <div class="task-date">
                                          <%= task.duetime.strftime("%D %l:%M %P") %>
                                      </div>
              
                                  </a>

                                   <div id= "<%= task.id %>" class="accordion-body collapse">
                                          <div class="accordion-inner">
                                              <%= task.description %>
                                            </div>
                                   </div>
                              </div>
                              <div class="col-md-4">
                                  Priority of task: <%= calcPriority(task).round(2) %> 
                                  How interested I am: <%= task.interest %> 
                                  Length: <%= task.length %> 
                                  <span class="delete_task"><%= link_to 'delete', task, remote: true, method: :delete%></span>
                              </div>
                          
                          </div>
            </div>
            </div>
              
        </li>

app/views/tasks/addtask.js.erb
$('#task_<%= @task.id %>').fadeOut().delay(500).queue(function(){
   $(this).remove()
})
$('#completed_list').append("<%=escape_javascript(render(@task))%>");

app/views/tasks/complete.js.erb
$('#task_<%= @task.id %>').fadeOut().delay(500).queue(function(){
   $(this).remove()
})
$('#completed_list').append("<%=escape_javascript(render(@task))%>");

app/views/tasks/destroy.js.erb
$('#task_<%= @task.id %>').fadeOut();

app/views/tasks/new.html.erb
<%= render "/demo2/header" %>

<% provide(:title, 'New Task') %>
<body style = "margin-top: 50px;">

	<div class="container">

	<div class="main-container">
		
		<div class="row">

			<div class="span4 offset4">
				<%= form_for @task, html: {class: "form-signin"} do |f| %>
					 <h2 class="form-signin-heading">New Task</h2>
					 <%= render 'shared/error_messages', object: @task %>

					<% if @task.errors.include?(:name) %>
					<div class="form-group has-error">
						<%= f.text_field :name, class:"form-control", html: { id: "inputError"},  placeholder:"Name" %>
					</div>
					<% else %>
					<div class = "form-group">
					 	<%= f.label :name, class: "sr-only" %>

						<%= f.text_field :name, class:"input-block-level", placeholder:"Name" %>
					</div>
					<% end %>

					<% if @task.errors.include?(:description) %>
					<div class="form-group has-error">
						<%= f.text_area :description, class:"form-control", size:"10x5", html: { id: "inputError"},  placeholder:"Description" %>
					</div>
					<% else %>
					<div class = "form-group">
					 	<%= f.label :description, class: "sr-only" %>
						<%= f.text_area :description, class:"form-control", size:"10x5",  placeholder:"Description" %>

					</div>
					<% end %>
					
					<div class = "form-group">
					 	<%= f.label :interest, class: "sr-only" %>
						<%= f.number_field :interest, placeholder: "How interesting is this task?", html: {max:"10", min: "1"}%>

					</div>	
					<div class = "form-group">
					 	<%= f.label :length, class: "sr-only" %>
						<%= f.number_field :length, placeholder: "How many hours will it take?", html: {max:"10", min: "1"}%>

					</div>		
					<div class="form-group">
					  <div id="datetimepicker1" class="input-append date">
					  	<%= f.label :duetime, class: "sr-only" %>

					  	<%= f.text_field :duetime, class: "input-block-level", 'data-format'=> "MM/dd/yyyy HH:mm:ss PP", placeholder: "Due time"%>
					    <span class="add-on">
					      <i style = "height: 50px" data-time-icon="icon-time" data-date-icon="icon-calendar">
					      </i>
					    </span>
					  </div>
					</div>
					<script type="text/javascript">
					  $(function() {
					    $('#datetimepicker1').datetimepicker({
					      language: 'en',
					      pick12HourFormat: true,
					      

					    });
					  });
					</script>
					<div class = "form-group">
					 	<%= f.label :completed, class: "sr-only" %>
						<%= f.hidden_field :completed, value: false %>

					</div>
					<div class = "form-group">
					 	<%= f.label :id, class: "sr-only" %>
						<%= f.hidden_field :id, value: current_user.id %>

					</div>			
							
					
					<%= f.submit "Create Task", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
	</div>
	</body>

app/views/tasks/show.html.erb
<%= @task.name %>, <%= @task.description %>

app/views/tasks/uncomplete.js.erb
$('#task_<%= @task.id %>').fadeOut().fadeOut().delay(500).queue(function(){
   $(this).remove()
})
$('#todo_list').append("<%=escape_javascript(render(@task))%>");

app/views/users/edit.html.erb
<%= render "/demo2/header" %>

<% provide(:title, 'Update your profile') %>


    <div id = "wrap">
	<div class="container">

	<div class="main-container">
		
		<div class="row">

			<div class="span4 offset4">
				<%= form_for @user, html: {class: "form-signin"} do |f| %>
					 <h2 class="form-signin-heading">Update Your Profile</h2>
					 <%= render 'shared/error_messages' %>

					<% if @user.errors.include?(:name) %>
					<div class="form-group has-error">
						<%= f.text_field :name, class:"form-control", html: { id: "inputError"},  placeholder:"Name" %>
					</div>
					<% else %>
					<div class = "form-group">
					 	<%= f.label :name, class: "sr-only" %>

						<%= f.text_field :name, class:"input-block-level", placeholder:"Name" %>
					</div>
					<% end %>

					<% if @user.errors.include?(:email) %>
					<div class="form-group has-error">
						<%= f.text_field :email, class:"form-control", html: { id: "inputError"},  placeholder:"Email" %>
					</div>
					<% else %>
					<div class = "form-group">
						<%= f.label :email, class: "sr-only" %>
						<%= f.text_field :email, class:"input-block-level", placeholder:"Email" %>
					</div>
					<% end %>

					<%= f.label :password, class: "sr-only" %>
					<% if @user.errors.include?(:password) %>

					<div class="form-group has-error">
						<%= f.password_field :password, class:"form-control", html: { id: "inputError"},  placeholder:"Password" %>
					</div>
					<% else %>
					<div class = "form-group">
						<%= f.password_field :password, class:"input-block-level", placeholder:"Password" %>
					</div>
					<% end %>

					<%= f.label :password_confirmation, "Confirmation",class: "sr-only" %>

					<% if @user.errors.include?(:password_confirmation) %>
					<div class="form-group has-error">
						<%= f.password_field :password_confirmation, class:"form-control", html: { id: "inputError"},  placeholder:"Confirm" %>
					</div>
					<% else %>
					<div class = "form-group">
						<%= f.password_field :password_confirmation, class:"input-block-level", placeholder:"Confirm" %>
					</div>
					<% end %>
					<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
	</div>
	</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>